### PR TITLE
Fixing humbug classbinding to stop throwing exceptions all the time if Humbug isnt loaded

### PR DESCRIPTION
**Pull request by Maxopoly**
Fixing https://github.com/Civcraft/Bastion/issues/23

Making this as a pull request because I cant build it locally to test it, so I just wanted someone to take a second look.

### CODE REVIEW

**Comment by ttk2** [comment]
looks good, @rourke750  thoughts?

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
huh, need to add bastion.  Looks good otherwise.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Pull request closed without merging**
