### PR TITLE
Update BastionBlock.java

### PR DESCRIPTION
**Pull request by TealNerd**
Added database connection checks before prepared statements

### CODE REVIEW

**Comment by ttk2** [comment]
Update on Civtest? Also could we get this for rb too? Citadel and NameLayer
dont have this problem right?

**Comment by erocs** [comment]
Yes push to civtest as that was where the disconnect surfaced.

**Comment by ttk2** [comment]
on civtest

**Comment by TealNerd** [comment]
I can't find where the database stuff is in rb or i would update that too

**Pull request merged**
