### PR TITLE
API update

### PR DESCRIPTION
**Pull request by suirad**
Changed two methods so that other plugins can check if a location is within a bastion field(s)

### CODE REVIEW

**Comment by suirad** [comment]
@ttk2 good for merge

**Comment by suirad** [comment]
Good to merge @ttk2 @rourke750

**Comment by drjawa** [comment]
You just need to sign the CLA real quick: https://www.clahub.com/agreements/Civcraft/Bastion

**Comment by jjj5311** [comment]
@drjawa is it possible to just make a CLA for the civcraft organization? like sign one and it is good for all?

**Comment by rourke750** [comment]
I don't believe so and not every repo has the same license.

**Comment by jjj5311** [comment]
dang that would have been nice

**Comment by suirad** [comment]
CLA is signed.

**Comment by drjawa** [comment]
Bah for some reason it still says that not all contributors have signed the CLA.

**Comment by rourke750** [comment]
Have you?

**Comment by drjawa** [comment]
I have never signed one before and didn't have any warning about it. I went ahead and signed it anyway but it's still complaining.

**Comment by suirad** [comment]
I just resigned it again.

**Comment by drjawa** [comment]
There we go.

**Comment by drjawa** [comment]
So now we just need to sort out the random-spawn pulls and we can test this.

https://github.com/Civcraft/random-spawn/pull/4

https://github.com/Civcraft/random-spawn/pull/3

**Comment by ttk2** [comment]
merged, but no build from jenkins.

**Pull request merged**
