### PR TITLE
Allow square fields and non midair blocking

### PR DESCRIPTION
**Pull request by Maxopoly**
@rourke750 @ProgrammerDan 

That should do the trick, shouldn't it? It should also be safe for other server to upgrade their version and not their config, without anything changing for them.

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
Might want to make including Y level of bastion as a config option too, otherwise this looks awesome.

**Comment by Maxopoly** [comment]
I figured that any other server running Bastion (are there even any aside from Devoted?) would want this change anyway, so why bother with a config option

**Comment by ProgrammerDan** [comment]
I have no idea how many, but it's a noticeable balance change by itself.

**Comment by Maxopoly** [comment]
Eh, convinced.


Should I merge or should we put the test build on CivTemp?

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
Nevermind, seems like the build server doesn't want to make another build for this pull.

**Comment by IAPark** [comment]
I don't see where it modify pearl blocking to work with a square field, this is definitely doable, but honestly the code that deals with that is both the most complicated and the most badly designed code in Bastion so it's the biggest reason I haven't done it

**Comment by IAPark** [comment]
Basically right now Bastion attempts to calculate the first time time the pearl can possible cross into a blocking field and therefore can just check back then and check if the pearl is actually still around and if so destroy it.

**Comment by IAPark** [comment]
If you guys are planning on removing blocking in mid air though it probably will work fine, you may want to for efficiency reasons though block the calculations when the pearl is first thrown would probably be better. Like say right here https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/listeners/EnderPearlListener.java#L40

**Comment by IAPark** [comment]
And I'd also be very careful to make sure the non mid air blocking works properly. It was put in as a sanity check more than anything, I'm not sure that it works perfectly at the moment. Probably it's fine, because it's much simpler, but I'm not sure.

**Comment by IAPark** [comment]
I'll also restate the justification for not including the same y level that the block is on. The thinking was that, especially for places without the bed rock, allowing blocks to always be placed on the y level the block is on would mean that people could always bridge over to destroy the physical block. Without this Bastions become significantly more powerful in regions without a bedrock floor.

**Comment by Maxopoly** [comment]
Wait so the code to block pearls is not just using the location check of the bastion block? I saw that 400 line monster that's supposed to check whether a pearl is in the area, but I had hoped I could just change the method in BastionBlock and it would work.


If that's not the case I'll just rewrite the pearl blocking code, I have no clue what's going on there and it's insanely over complicated. The only thing you would need is a runnable, which checks whether the pearl is in a bastion field on every tick.

**Comment by IAPark** [comment]
Your probably right, the worry at the time was that the computation for that would get too expensive. It would be something like log(n)*m where n is the number of Bastions in the world and m is the number of pearls flying at any moment, and that's every tick. I don't have numbers on how many pearls ended up getting used though and I certainly remember that pearl blocking was a minor part of Bastions time.

**Comment by Maxopoly** [comment]
This is using a quadtree as far as I can see, if you simply get all the bastion in the area over that and then do the detailed check on each of those you can do it without any noticeable performance hit.

**Comment by ProgrammerDan** [comment]
Total number of inflight pearls is limited to player cap anyway; the total amount of time is negligible given the quadtree.

**Comment by IAPark** [comment]
quadtree has log(n) look up right? It's basically a 2d binary search tree yes

**Comment by IAPark** [comment]
But I think @ProgrammerDan is right that the actual number of pearls in flight should be low enough that it shouldn't mater

**Comment by ProgrammerDan** [comment]
Should be log(n) as an upper bound, yeah, if the one we're using is well-structured. So you're looking at O(log(n)*onlineplayers) where online players on a given single server instance is likely < 200.

**Comment by IAPark** [comment]
It's definitely worth a try and would certainly vastly simplify the code. I do recall we had negative performance initially before we properly implement a priority queue when we were checking every pearl

**Comment by IAPark** [comment]
As a quick check you should be able to just modify this https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/manager/EnderPearlManager.java#L342

**Comment by IAPark** [comment]
You may also want to modify the creation of the quad tree if we'll no longer ever going to be looking them up in a big area. It's probably not particularly efficient right now because it has padding set very large which to be honest might make up for any efficiency lost here anyway. The biggest time usage was for pistons which also has something like O(log(n)m) complexity and a decently large constant.

https://github.com/Civcraft/Bastion/blob/master/Bastion/src/isaac/bastion/storage/BastionBlockSet.java#L71

**Comment by IAPark** [comment]
I never really did understand space quad tree though partially because I first saw it before I'd taken a database course. I suspect the complexity is the same as that goes up, but the constant goes way up.

**Comment by ProgrammerDan** [comment]
So I'm going to go ahead and merge this, then demux the math tomorrow night. Thanks for the comments and insight, @IAPark !

**Comment by IAPark** [comment]
I'm was reading the AMA about Bastions and it sounds like you want people to be able to pearl out of a field even if they are blocked. With this modification that still won't work. There's a check for where people are teleporting from so it should still get blocked.

https://github.com/Maxopoly/Bastion/blob/50a94e0f5759ac8025544f457903383e20277862/Bastion/src/isaac/bastion/manager/BastionBlockManager.java#L370-L394

**Comment by ProgrammerDan** [comment]
Good catch. Mind putting it into a top level issue for me?

**Pull request merged**
